# Site settings
title: Rui Peng
description: >
  Enthusiatic Programmer graduated from HKUST

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://raypeng.com" # the base hostname & protocol for your site
# url: "http://localhost:4000" # for testing locally

author:
  fullname: Rui Peng
  email: pengrui1993@gmail.com
  github: raypeng
  twitter: rayrpeng
  linkedin: rui-ray-peng/6a/194/a12
  # stackoverflow: 2255305
  # disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: kramdown

# try out github favored markdown
kramdown:
  input: GFM
