# Site settings
title: Rui Peng
description: >
  Enthusiatic Programmer graduated from HKUST

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://raypeng.github.io" # switch back to github pages
# url: "http://raypeng.com" # the base hostname & protocol for your site
# url: "http://localhost:4000" # for testing locally

author:
  fullname: Rui Peng
  email: pengrui1993@gmail.com
  github: raypeng
  # twitter: rayrpeng
  linkedin: rui-ray-peng/6a/194/a12
  disqus: ruipeng
  # stackoverflow: 2255305

google_analytics: 'UA-66241777-2'

# Build settings
markdown: kramdown

# try out github favored markdown
kramdown:
  input: GFM
